### ISSUE TITLE
pip3 install pygame

### ISSUE THREAD

**Issue by jeromeEzDATASolutions** [dciabrin/ngdevkit#107]
ngdevkit compil ok
but now ive this error 👍 
<img width="1465" alt="Capture d’écran 2024-03-14 à 08 29 10" src="https://github.com/dciabrin/ngdevkit/assets/107132830/4044c5c3-815e-4ead-8aee-063be2f406fc">

**Comment by jeromeEzDATASolutions** [comment]
i use --break-system-packages and its ok
but now it's not possible to comile a game
<img width="1448" alt="Capture d’écran 2024-03-14 à 08 36 08" src="https://github.com/dciabrin/ngdevkit/assets/107132830/95c39487-4e4f-46d6-b41f-71215a8962c9">

**Comment by dciabrin** [comment]
Thanks for reporting the pip3 breakage, that's a new warning in brew apparently..
While one can install pygame in a virtualenv for cleaner install, brew currently doesn't ship pygame, so for the time being it's safe to use  --break-system-packages.
I'll update the main doc accordingly.

As for your second warning, this has nothing to do with pip.
If the makefile is derived from ngdevkit-examples, it probably means the 68k compiler from ngdevkit-toolchain was not found in path, and got configured incorrectly:
```
$(M68KGCC) $(NGCFLAGS) -std=gnu99 -fomit-frame-pointer -g -c $< -o $@
```
Check whether M68KGCC is set to something in Makefile.config.
Otherwise, please update ngdevkit-examples and re-run ./configure

**Comment by jeromeEzDATASolutions** [comment]
all is ok
Thlanks a lot
