### ISSUE TITLE
ngdevkit installation 

### ISSUE THREAD

**Issue by ozzyOuzo** [dciabrin/ngdevkit#2]
Hello :)

First of all i have to say that i'm more a windows user/coder than a gnu/linux expert :)

But as this project look so much interesting and has also so much potential for 'modern' neogeo coding, i'm ok to do my part using gnu/linux and command line crazyness ^^

So far, i've tested on fresh installations of debian 9.4 and debian 8.10 (tiny cd + network installation, without going through important updates though) and i was unable to survive to 'make' which is generating a long list of problems (i think there is a main issue concerning binutils)

Before reaching this point, there were missing/wrong informations from your pre-requisite section concerning the installation of required packages. For instance libsdl2.0-dev doesn't match libsdl2-dev and some missing packages to list a few are : bison, flex, curl and so on.. Maybe also a special attention would be needed when trying to compile examples about external pythongame program.

I know, that it is *not* the most interesting part for a maintainer but for completely new users like me who couldn't be gnu/linux friendly aswell you should:

- Not too much assume what is evident and what are the normally pre-installed packages on a distro as an experimented gnu/linux user.
- Add every command line involved with all required package installation before reaching gcc/scc 'make'
(it could looks silly but is so important for newcomers.)
- Try it out yourself as a maintainer on fresh distros to be sure that any user interested by ngdevkit will be able to complete the installation flawlessly. ;-)

That's it, i hope to be able to install ngdevkit soon or later!

Hope this helps and keep on the good work!

Ozzy.

**Comment by ozzyyzzo4096** [comment]
adding a screenshot of the problem [https://www.jeuxdecartes.ovh/data/binutils.jpg](url)

**Comment by dciabrin** [comment]
Hey, it's been some time that I didn't compile the devkit on a debian-based distro.
I'll have a look at what's needed on a recent debian-based VM and adapt the readme accordingly.

Maybe we also want to track the Windows support in a dedicated issue

**Comment by dciabrin** [comment]
Hey ozzyyzzo4096,
Let's continue this thread in English for broader reach, no offense :)

So the dependencies section was incorrect and outdated, sorry about that.
- I fixed typo in the name of libsdl and install curl, thanks
- Instruction have been updated to download all the depencies of gcc-{version}-base instead of gcc, so you'll download automatically bison, texinfo and all the others.
- Added a section for the dependencies of SDCC, since it's been introduced recently.

The problem you're having for building binutil comes from the fact that curl was missing, so the Makefile ended up creating a empty binutils-2.25.tar.bz2 instead of the expected archive, so later build would fail.
Upgrade to the latest commit and do a "make distclean && make", that should fix your issue.

**Comment by ozzyyzzo4096** [comment]
Hey,

Installation is now ok!
For some reasons, the command : apt-get install graphicsmagick-imagemagick-compat
was required before 'apt-get build-dep sdcc' on my distro (debian 9.4).

Compiling and testing 'hello world' sample through the emulator is working like a charm aswell!!

Very nice work Damien!! 

now time for some coding :)

Ps: i will try the installation through cygwin and let you know if i'm facing any specific issues into another thread.

**Comment by dciabrin** [comment]
Hey

I'm closing this issue now, as the last dependency issue you reported has been resolved in 9f763fc472be5e1f03496e91df54c4f2fa373008
