### ISSUE TITLE
Can you make a MSYS toolchain installer for windows

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [dciabrin/ngdevkit#47]
Hello, I want a easy way to develop neo geo aes/MVS games on windows but I can't get the toolchain or the commands to work for installing ngdevkit on windows 10 so can you please make a MSYS toolchain!

**Comment by dciabrin** [comment]
As expected, this is a can of worm...
But progress has been made already, I can build locally gngeo, gcc, binutils, newlib and sdcc with mingw-gcc.
gdb is still causing me troubles, as we need GDB 9 to support python3 on windows.
Also, we don't have a package for PyGame in MSYS2, which means we'll need to rely on an official build of Python3 for windows. Which as it turns out, causes additional issues with shebangs in titletool and paltool.. This one is less serious, but it's a gap.

I'll continue pushing incremental fixes to get there.

**Comment by dciabrin** [comment]
With commit https://github.com/dciabrin/ngdevkit/commit/f845e9c40fb9c8f6ee562933fb08a311785667ae, you can now build the entire devkit natively on msys2.
This is not as easy as installing packages with pacman, but that's a first step towards it.

I'm keeping that issue opened until I provide packages for msys2, but this is yet another big milestone.

Meanwhile, I would encourage you to give the msys2 compilation a try if you need native windows support.

**Comment by dciabrin** [comment]
Yes it's pretty rough currently because this is all a moving target and I keep fixings the subprojects any time I reach a new issues.
The good news i have a few commits in ngdevkit-examples to merge and with those I can consistently consume the MSYS2 packages now (for which there's no public doc right now).

The bad news is that this work on packaging made me changes bits here and there and I don't have CI jobs for building from source according to the current README.

So that's two things to fix until we can claim MSYS2 support.

**Comment by dciabrin** [comment]
Done!

Nightly binary packages are now available for MSYS2, are are automatically updated on each commit in git.
Have a look at the updated README.md and don't hesitate to give feedback.
