### ISSUE TITLE
Issue with checksum in Mame

### ISSUE THREAD

**Issue by totologic** [dciabrin/ngdevkit#5]
After compiling the 01-helloworld example, I try to run the rom in Mame but it doesn't work, always leading to checksum issues. I tried few simple set-up:

Set-up n1:
Mame32 0.65
1 rom :
- puzzlebobble found on the internet

bios :
- some bios found on the internet

Result :
- puzzlebobble works fine

Set-up n2:
Mame32 0.65 (same as set-up n1)
2 roms :
- puzzlebobble, found on the internet (same as set-up n1)
- puzzledp, result of 01-helloworld example compilation

bios :
- some bios found on the internet (same as set-up n1)

Results :
- puzzlebobble works fine
- puzzledp doesn't pass the audit of Mame and couldn't be run:  INCORRECT CHECKSUM

Set-up n3:
Mame32 0.65 (same as set-up n1)
2 roms :
- puzzlebobble, found on the internet (same as set-up n1)
- puzzledp, result of 01-helloworld example compilation (same as set-up n2)

bios :
- the compiled nullbios

Results : both puzzlebobble and puzzledp leads to INCORRECT CHECKSUM errors

Did I miss something ?

**Comment by totologic** [comment]
OK it was a noob issue.

My solution if it could help other noobs. In MAME just use a regular BIOS as it can be found on the internet. Once compiled an example, just run the puzzledp.zip rom under the name "Puzzle De Pon" in MAME. Don't worry about the checksum, it is optional.

**Comment by dciabrin** [comment]
So to elaborate a bit on the generated rom and the arbitrary names chosen for them:
All Neo-Geo emulators have a hardcoded ROM-list that they know about. They need it because not all NeoGeo ROMs are treated equally: some have bigger graphics ROM size, some have special addressing mode,... so all those peculiarities are usually described in the emulator's ROM-list.

This has two consequences for ngdevkit:
  * For a ngdevkit-based ROM to be runnable in an emulator, it has to be named like a known ROM.  puzzledp was the arbitrary ROM I came up with when I pushed the examples.
  * Emulators sanity check ROM before running it, so since a ngdevkit ROM has nothing in common with an original ROM, all emulators complain about checksum mismatch. That's an expected downside.

I've tested the generated ROMs from example-01 with mame32 0.65 on windows. This MAME version has a very old ROM-list, and so the name of the files inside the nullbios zip don't match with what MAME expects.

Is there any particular reason that you would need this old mame, instead of more recent ones, or even the gngeo version included in the devkit?

**Comment by totologic** [comment]
Absolutly no preference for this MAME version, it was just the old one rusting on my computer :)

**Comment by dciabrin** [comment]
OK, so I'm considering closing this issue accordingly. I'm not sure I want to add bloat to nullbios for an old version of mame :)

**Comment by dciabrin** [comment]
Quick heads up, I'll close that lingering issue as it seems recent versions of MAME are able to run user's ROM with nullbios.
