### ISSUE TITLE
Vertical shrinking & garbage

### ISSUE THREAD

**Issue by tatsunootoshigo** [dciabrin/ngdevkit#72]
Hi @dciabrin! I m still playing with your devkit and I m a bit stuck with an issue with vertical shrinking.
I have read [this](https://wiki.neogeodev.org/index.php?title=Sprite_shrinking) and pretty much everything on the wiki but maybe I missed something at some point.
I have computed the "window" height (expressed in tiles) according to the zoom factor and everything is fine when the computed sprite height is a multiple of 16 (meaning the "window" size match exactly the computed sprite height).
However, I have some garbage on screen when I end up having a larger window than the actual sprite height. Exactly like the yellow tile in the link above ([here is an example](https://wormhole.app/Wv9dA#NmS2yGsc2HNFsuPz6vvbFA)).
Thanks to @city41 I have read it may be because those lines are filled with tile #255. But I checked the content of the both SROM and CROMs with @city41 tile viewer and tile #255 are effectively empty.
I can also notice the color of the garbage is defined by the first palette in use, meaning the fixmap palette. So that is leading me to believe its related to the fixmap but I cant figure out whats wrong.
Have you experienced this kind of glitch? 
I hope I m clear enough, thanks for your help!

**Comment by tatsunootoshigo** [comment]
> But I checked the content of the SROM with @city41 tile viewer and this tile is effectively empty.
Actually both SROM and CROM tile #255 are empty.

**Comment by city41** [comment]
[This thread might help](https://neo-geo.com/forums/index.php?threads/vertically-scaling-sprites-on-real-hardware-avoiding-graphical-artifacts.267385/)  
  
When the window height is taller than your tiles, the garbage is coming from the next tiles in the sprite's tile map.

So let's say you specify 4 tiles for a sprite, give it a height of 4, and then shrink it in half. The four tiles you defined will take up 32px of the window, and the next 32px will be determined by tiles 5, 6, 7 and 8. Those tiles will just be whatever happens to be in VRAM. A lot of the times, leftover VRAM is `0xff`, as it seems the Neo initializes VRAM to that. But it can be anything just depends on what has happened to VRAM in your game.

Things get much weirder when you start working with sprites taller than 16. That neo-geo thread goes into that a bit.

**Comment by city41** [comment]
![image](https://user-images.githubusercontent.com/141159/149626707-495bd161-d783-4668-84fa-2ddb44df016b.png)

This is from that neo-geo thread. Here I wrote `0` to all VRAM memory addresses before starting the test, and I defined the first tile in my C ROM to be that square pattern. So in my case the garbage tiles became that square pattern due to VRAM having `0` for those tiles.

**Comment by tatsunootoshigo** [comment]
Thats exactly my issue!
My garbage pattern comes from CROM tile #0.
Thanks a lot for pointing it out!
Cheers

Oh and I will be interested to see the results of your ala AOF scaling :+1:

**Comment by city41** [comment]
Awesome! Glad that fixed it.

I gave up on my scaling idea. My game no longer zooms in/out unfortunately. The problem is the Neo can only scale in 16 increments, and so no matter what my scaling was super janky. I think if you want to do zoom in/out like SNK fighters did, you are mostly limited to a 32 tile tall level that has one major axis, basically fight game stages. Unless there is a really awesome trick I don't know about. Ah well, it's an old system :)

**Comment by tatsunootoshigo** [comment]
Thats awesome you are making a game! 
Cant wait to see that :)

**Comment by dciabrin** [comment]
Obviously I'm late at that, but I'm glad y'all sorted out!

Thanks for the links, this is very informative and hopefully it will be useful in the future.

**Comment by tatsunootoshigo** [comment]
Its all good no worries. Thank you for your work!
