### ISSUE TITLE
failed to install on macos brew

### ISSUE THREAD

**Issue by nareez** [dciabrin/ngdevkit#74]
Some links are not downloading, so brew could not finish installation 

Broken links:
https://github.com/dciabrin/ngdevkit-toolchain/archive/nightly-202104282019.tar.gz
https://github.com/dciabrin/gngeo/archive/nightly-202111141729.tar.gz

**Comment by dciabrin** [comment]
Thanks for reporting the issue,

This is due to the deprecation of old macos image in azure pipelines's hosted builders. I need to fix the CI configuration to only build for macos 11 and 10.5.

I also need to fix the way the old tags are cleaned up in git repos, to be less agressive and keep them as long as any binary package (mac,linux,msys2) still reference them. This will be tracked in another bz as it's a more involved change.

**Comment by nareez** [comment]
I tried to install it today and everything worked fine. I think the problem has been solved

**Comment by dciabrin** [comment]
Hmmm, not sure what that would be the case because nothing new was pushed..

As a heads up, I'm currently reworking how repo ngdevkit-toolchain builds in CI and i stumbled upon a lot of new compilation failures with clang-13 on the latest macos image in github CI.
Once those will be fixed and build becomes compatible with latest gcc and clang, I'll push new revisions in master branch and new bottles for macos11.
