### ISSUE TITLE
Remove sprites/tiles  from screen

### ISSUE THREAD

**Issue by totologic** [dciabrin/ngdevkit#8]
Hi.

If we consider the 02-sprite example, how could I remove properly a sprite from screen ? Same question for removing a single tile belonging to a sprite ?

At the beginning of the program, you use the value 255 as the rank of a transparent tile in BIOS ROM to clear the tiles of the fix map. Does it mean my 255th tile in c-ROM is compulsorily overwriten by this transparent tile ?

Using an empty tile to "clear" sprites or tiles should work but it looks like a waste of ressources for me. Maybe my point of view is wrong ?

**Comment by totologic** [comment]
For sprites, setting the height parameter to 0 in SCB3 for the lead sprite do the job. Do you know if we have a better choice ?

**Comment by dciabrin** [comment]
> If we consider the 02-sprite example, how could I remove properly a sprite from screen ? Same question for removing a single tile belonging to a sprite ?

I don't know if there's a single best answer to your question, setting the height looks like a fairly fast way to do that. I was thinking of moving the offset of the sprite off-screen, but it seems an equally fast option.

> At the beginning of the program, you use the value 255 as the rank of a transparent tile in BIOS ROM to clear the tiles of the fix map. Does it mean my 255th tile in c-ROM is compulsorily overwriten by this transparent tile ?

No that's a arbitrary choice on my side, because the c-ROM in the original BIOS has an empty tile at that offset. So if you use an original ROM in place of ngdevkit's nullbios, you would reuse that tile (and have a nice eyecatcher intro at boot time for free :)) 

> Using an empty tile to "clear" sprites or tiles should work but it looks like a waste of ressources for me. Maybe my point of view is wrong ?

Yes, definitely a waste of CPU cycles.

**Comment by dciabrin** [comment]
> For sprites, setting the height parameter to 0 in SCB3 for the lead sprite do the job. Do you know if we have a better choice ?

Obviously it's been a while since you opened the issue and you already have a full game running... but for the sake of the discussion I'm going to add two pointers to the neogeodev wiki here before closing that issue:

  1. the [hello world](https://wiki.neogeodev.org/index.php?title=Hello_world_tutorial) tutorial from the wiki does exactely what you said: it cleans the sprite's hight for all sprites. So that seems a fairly quick way to achieve clean up.

  2. There's BIOS function [LSP_1st](https://wiki.neogeodev.org/index.php?title=LSP_1st) dedicated to that purpose. It's doing a more thorough clean up, as explained in the wiki.

Kudos to the folks at [neogeodev](https://wiki.neogeodev.org) for their invaluable information.
