### ISSUE TITLE
Games no longer work in MAME

### ISSUE THREAD

**Issue by city41** [dciabrin/ngdevkit#97]
I have the ngdevkit-examples repo from 2021 and still have all the built binaries from that time. When I run those binaries in MAME, they work as expected. If I recompile them with the current version of ngdevkit, MAME drops into the MVS settings (as if hardware dipswitch 1 is on). The roms still work as expected in gngeo.

Based on these binaries coming form November 2021, I am assuming I was using version 0.2. I am now using version `0.2+202306062054-13~ubuntu20.04.1`

I notice apt does not have 0.2. I'll see if I can compile it and use it without apt.

I am doing

```
cd 05-scrolling
cp rom/puzzledp.zip ~/mame/roms
mame -w puzzledp
```

The particular example doesn't matter.

This is when I last compiled
```
13:17 $ ls --full-time rom
total 1304
lrwxrwxrwx 1 matt matt       9 2021-11-24 20:47:26.630990184 -0500 202-c1.bin -> 202-c1.c1
-rw-rw-r-- 1 matt matt 1048576 2021-11-24 20:47:26.622990337 -0500 202-c1.c1
lrwxrwxrwx 1 matt matt       9 2021-11-24 20:47:26.630990184 -0500 202-c2.bin -> 202-c2.c2
-rw-rw-r-- 1 matt matt 1048576 2021-11-24 20:47:26.626990261 -0500 202-c2.c2
lrwxrwxrwx 1 matt matt       9 2021-11-24 20:47:26.630990184 -0500 202-m1.bin -> 202-m1.m1
-rw-rw-r-- 1 matt matt  131072 2021-11-24 20:47:26.626990261 -0500 202-m1.m1
lrwxrwxrwx 1 matt matt       9 2021-11-24 20:47:26.630990184 -0500 202-p1.bin -> 202-p1.p1
-rwxrwxr-x 1 matt matt  524288 2021-11-24 20:47:26.214998081 -0500 202-p1.p1
lrwxrwxrwx 1 matt matt       9 2021-11-24 20:47:26.630990184 -0500 202-s1.bin -> 202-s1.s1
-rw-rw-r-- 1 matt matt  131072 2021-11-24 20:47:26.626990261 -0500 202-s1.s1
lrwxrwxrwx 1 matt matt       9 2021-11-24 20:47:26.630990184 -0500 202-v1.bin -> 202-v1.v1
-rw-rw-r-- 1 matt matt  524288 2021-11-24 20:47:26.626990261 -0500 202-v1.v1
drwxrwxr-x 2 matt matt    4096 2022-01-15 17:43:38.597008435 -0500 history
-rwxr-xr-x 1 matt matt    5602 2021-11-24 20:47:26.662989576 -0500 neogeo.zip
-rw-rw-r-- 1 matt matt   36304 2021-11-24 20:47:26.662989576 -0500 puzzledp.zip
```

Ubuntu 20.04.6
Mame 0.220
ngdevkit 0.2+202306062054-13

I will also see if I can figure this out. But posting an issue in case anyone knows right away.

**Comment by city41** [comment]
Ah ha, I failed to notice my Makefiles were a few commits back.

At this commit - 547bf6d07870ebe63e36c9e322cdfbfa7cdbd838, the game do not work in MAME.

At the latest commit, they do. 

Looks like I need to incorporate the Makefile changes into my game to get it running again, but that's on me.

**Comment by city41** [comment]
For completeness, it was padding out the prom that needed to change. Here is my Makefile diff

```
+PROMSIZE:=524288
 $(PROM): $(ELF) | rom
-       $(M68KOBJCOPY) -O binary -S -R .comment $< $@ && dd if=$@ of=$@ conv=notrunc,swab
+       $(M68KOBJCOPY) -O binary -S -R .comment --gap-fill 0xff --pad-to $(PROMSIZE) $< $@ && dd if=$@ of=$@ conv=notrunc,swab
```

**Comment by dciabrin** [comment]
Ah! good to know that you found out where you issue was..

Indeed it turns out that I sometimes introduced breaking changes in ngdevkit, assuming that ngdevkit and ngdevkit-examples would always be kept in sync, assuming they would not be a major hurdle. Bad assumption...

I'll try to announce breaking changes more clearly in the future. I'll bump ngdevkit version on the next major change, and tag the commit to ease backtracking in case one needs to troubleshoot something.

I think that ngdevkit is still a moving target, so in the immediate future I'll keep providing binary packages for nightly builds only, I don't think packaging stable releases is worth the effort just yet.

NB: I'm about to push a breaking change by re-implementing the z80 sound driver, to ease the implementation of future improvements.

Thanks for your bug report.
